// <auto-generated />
namespace CarToGoAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class GPSCondinatUpdate3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GPSCondinatUpdate3));
        
        string IMigrationMetadata.Id
        {
            get { return "201912242140352_GPSCondinat-Update-3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
